workflows:
  android-workflow:
    name: Build Flutter APK
    instance_type: mac_mini_m1
    environment:
      flutter: latest
      java: 17
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: |
          flutter build apk --debug --no-tree-shake-icons
          ls build/app/outputs/flutter-apk/
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
