workflows:
  android-workflow:
    name: Build Flutter APK
    instance_type: linux_x2
    environment:
      flutter: 3.19.0
      java: 17
    scripts:
      - name: Install dependencies
        script: flutter packages pub get
      - name: Build APK
        script: flutter build apk --debug --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
