name: jaynes_max_tv
description: JAYNES MAX TV App
version: 5.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  onesignal_flutter: ^5.2.5

flutter:
  uses-material-design: true
